server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:13306/cms_web
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.1.101:9300
      repositories:
        enabled: true

